import test from 'node:test';
import assert from 'node:assert/strict';
import {buildBackup,validateBackup,decodeBackupValue,BACKUP_COLLECTIONS} from '../backup.mjs';
import {restoreMissing} from '../scripts/restore-backup.mjs';
const makeTimestamp=(seconds,nanoseconds)=>({seconds,nanoseconds,toDate:()=>new Date(seconds*1000)});
const makeBackup=()=>buildBackup(Object.fromEntries(BACKUP_COLLECTIONS.map(name=>[name,{docs:name==='users'?[{id:'student',data:()=>({name:'María',updatedAt:makeTimestamp(1700000000,987654321)})}]:name==='reservations'?[{id:'historical',data:()=>({uid:'student',dateKey:'2026-01-05',portions:2})}]:[]}])));
function mockDb(){const records=new Map();return {records,collection:name=>({doc:id=>({path:name+'/'+id,get:async()=>({exists:records.has(name+'/'+id)})})}),runTransaction:async fn=>fn({get:async ref=>({exists:records.has(ref.path)}),create:(ref,data)=>{assert.equal(records.has(ref.path),false);records.set(ref.path,data);}})};}
test('Respaldo conserva Unicode, historial e IDs y fechas con nanosegundos',()=>{const b=validateBackup(JSON.parse(JSON.stringify(makeBackup())));assert.equal(b.collections.users[0].data.name,'María');const restored=decodeBackupValue(b.collections.users[0].data,makeTimestamp);assert.equal(restored.updatedAt.nanoseconds,987654321);assert.equal(b.collections.reservations[0].id,'historical');});
test('Rechaza otro proyecto, colección faltante, ID duplicado y fecha inválida',()=>{for(const mutate of [b=>b.projectId='otro',b=>delete b.collections.menus,b=>b.collections.users.push(b.collections.users[0]),b=>b.collections.users[0].data.updatedAt.nanoseconds=1e9]){const b=makeBackup();mutate(b);assert.throws(()=>validateBackup(b));}});
test('Simulación no escribe; recuperación crea faltantes, omite existentes y puede repetirse',async()=>{const db=mockDb(),backup=makeBackup();let r=await restoreMissing(db,backup,{makeTimestamp});assert.equal(r.missing,2);assert.equal(db.records.size,0);db.records.set('users/student',{name:'Nombre más reciente'});r=await restoreMissing(db,backup,{apply:true,makeTimestamp});assert.equal(r.restored,1);assert.equal(db.records.get('users/student').name,'Nombre más reciente');r=await restoreMissing(db,backup,{apply:true,makeTimestamp});assert.equal(r.restored,0);assert.equal(db.records.size,2);});
test('Recuperación de una persona no restaura otros perfiles',async()=>{const b=makeBackup();b.collections.users.push({id:'other',data:{name:'Otro'}});const db=mockDb();await restoreMissing(db,b,{apply:true,uid:'student',makeTimestamp});assert.equal(db.records.has('users/other'),false);assert.equal(db.records.has('users/student'),true);});

test('Respaldo v1 sigue siendo recuperable y v2 incluye asistencia y actividad',async()=>{const b=makeBackup();assert.equal(b.version,2);assert.ok(Array.isArray(b.collections.attendance));b.version=1;delete b.collections.attendance;delete b.collections.userActivity;assert.equal(validateBackup(b),b);const db=mockDb();await restoreMissing(db,b,{apply:true,makeTimestamp});assert.equal(db.records.size,2);});
