const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const {createRequire}=require('node:module');
const deps=createRequire(process.env.APP_TEST_DEPS||path.resolve('tests/package.json'));
const {JSDOM}=deps('jsdom');
(async()=>{
 const domain=await import('../domain.mjs');
 const backupTools=await import('../backup.mjs');
 const management=await import('../management.mjs');
 const templateTools=await import('../week-template.mjs');
 let capturedBackup=null,failBackupRead=false;
 const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://appomedoruner.vercel.app'});
 dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
 const document=dom.window.document,records=new Map(),listeners=[],writes=[];
 let authCallback;
 const next=new Date(domain.monday()+'T00:00:00Z');next.setUTCDate(next.getUTCDate());
 const week=next.toISOString().slice(0,10);
 let autoId=0;const ref=(...args)=>args.length===1&&args[0]?.path?{path:args[0].path+'/auto'+(++autoId)}:{path:args.filter(x=>typeof x==='string').join('/')};
 const snapshot=r=>{
  if(r.filter){const list=[...records].filter(([p,d])=>p.startsWith(r.path+'/')&&(!r.constraints||r.constraints.every(w=>!w.field||(w.op==='=='?d[w.field]===w.value:w.op==='>='?d[w.field]>=w.value:d[w.field]<w.value))));return {docs:list.map(([p,d])=>({id:p.split('/').at(-1),data:()=>d}))};}
  const data=records.get(r.path);return {exists:()=>!!data,data:()=>data};
 };
 const notify=()=>listeners.filter(x=>x.active).forEach(x=>x.cb(snapshot(x.ref)));
 const set=async(r,d,opts)=>{records.set(r.path,opts?.merge?{...records.get(r.path),...d}:d);writes.push(r.path);notify();};
 const ctx=vm.createContext({document,console,Date:class extends Date{constructor(...args){super(...(args.length?args:[week+'T09:00:00-03:00']));}static now(){return new Date(week+'T09:00:00-03:00').getTime();}},Map,Number,Object,String,JSON,Intl,Promise,...domain,...backupTools,...management,...templateTools,applyWeekTemplate:(...args)=>templateTools.applyWeekTemplate(...args,new Date(week+'T09:00:00-03:00')),RECAPTCHA_ENTERPRISE_SITE_KEY:"",downloadBackup:b=>{capturedBackup=b;},validateSelections:(selected,days,profile)=>domain.validateSelections(selected,days,profile,new Date(week+'T09:00:00-03:00')),
  auth:{},db:{},GoogleAuthProvider:class{setCustomParameters(){}},
  signInWithPopup:async()=>{},signOut:async()=>authCallback(null),onAuthStateChanged:(a,cb)=>{authCallback=cb;cb(null);},
  doc:ref,collection:(...args)=>({...ref(...args),filter:true}),query:(r,...constraints)=>({...r,constraints}),where:(field,op,value)=>({field,op,value}),orderBy:()=>({}),limit:()=>({}),
  onSnapshot:(r,cb)=>{const x={ref:r,cb,active:true};listeners.push(x);cb(snapshot(r));return()=>x.active=false;},
  getDoc:async r=>snapshot(r),getDocs:async r=>snapshot(r),getDocsFromServer:async r=>{if(failBackupRead)throw new Error("Sin conexión");return snapshot(r);},setDoc:set,deleteDoc:async r=>{records.delete(r.path);notify();},
  writeBatch:()=>{const pending=[];return {set:(r,d,opts)=>pending.push([r,d,opts]),delete:r=>pending.push([r,null]),commit:async()=>{for(const [r,d,opts]of pending){if(d===null){records.delete(r.path);notify();}else await set(r,d,opts);}}};},
  runTransaction:async(db,fn)=>fn({get:async r=>snapshot(r),update:set,set}),
  serverTimestamp:()=>({server:true}),Timestamp:{fromDate:d=>d},setInterval(){},confirm:()=>true,prompt:()=>'',FileReader:dom.window.FileReader
 });
 vm.runInContext(fs.readFileSync('app.js','utf8').replace(/^import .*;\n/gm,''),ctx);
 assert.equal(document.querySelector('#admin-nav').hidden,true);
 assert.equal(document.querySelector('#login-button').hidden,false);
 assert.equal(document.querySelector('#first-use').hidden,false);
 assert.equal(document.querySelector('#first-use-action').textContent,'Ingresar con Google');
 assert.equal(document.querySelector('#week-input'),null);
 assert.equal(document.querySelector('#profile-panel').hidden,true);
 document.querySelector('#profile-toggle').click();assert.equal(document.querySelector('#profile-panel').hidden,false);
 document.querySelector('#profile-toggle').click();assert.equal(document.querySelector('#profile-panel').hidden,true);
 assert.equal(document.querySelector('.sidebar').firstElementChild.className,'menu-card');
 authCallback({uid:'student',email:'student@example.com',displayName:'Alumno',emailVerified:true});
 assert.equal(document.querySelector('#first-use-action').textContent,'Completar mi perfil');
 records.set('users/student',{name:'Alumno',condition:'Alumno regular',diet:'Sin TACC',email:'student@example.com'});
 for(const date of domain.weekDays(week))records.set('days/'+date,{week,blocked:false,generation:0});
 authCallback({uid:'student',email:'student@example.com',displayName:'Alumno',emailVerified:true});
 assert.equal(document.querySelector('#admin-nav').hidden,true);
 document.querySelector('#download-backup').click();await new Promise(r=>setImmediate(r));assert.equal(capturedBackup,null);
 assert.equal(document.querySelector('#profile-form').hidden,false);
 assert.equal(document.querySelector('#profile-reminders').checked,true);
 document.querySelector('#profile-reminders').checked=false;
 document.querySelector('#profile-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setImmediate(r));
 assert.equal(records.get('users/student').reminderEmails,false);
 authCallback({uid:'student',email:'student@example.com',displayName:'Alumno',emailVerified:true});
 assert.equal(document.querySelector('#profile-reminders').checked,false);

 const check=selector=>{const e=document.querySelector(selector);assert.ok(e,selector);e.checked=true;e.dispatchEvent(new dom.window.Event('change',{bubbles:true}));};
 check('[data-day="'+week+'"]');
 check('[data-date="'+week+'"][data-shift="mediodia"]');
 check('[data-date="'+week+'"][data-shift="noche"]');
 assert.equal(document.querySelector('[data-field="diet"]').value,'Sin TACC');
 assert.equal(document.querySelector('#pending-reservation').hidden,false);
 document.querySelector('#save-button').click();await new Promise(r=>setImmediate(r));
 assert.equal(writes.filter(p=>p.startsWith('reservations/')).length,2);
 assert.equal(document.querySelector('#first-use').hidden,true);
 assert.equal(document.querySelector('#pending-reservation').hidden,true);
 assert.match(document.querySelector('#save-message').textContent,/confirmada/);
 const toggle=document.querySelector('[data-toggle-day="'+week+'"]');assert.ok(toggle);
 toggle.click();assert.equal(document.querySelector('#details-'+week).hidden,true);
 assert.equal(document.querySelector('[data-toggle-day="'+week+'"]').getAttribute('aria-expanded'),'false');
 document.querySelector('[data-toggle-day="'+week+'"]').click();
 assert.equal(document.querySelector('#details-'+week).hidden,false);
 assert.equal(writes.filter(p=>p.startsWith('reservations/')).length,2);
 const cancelButton=document.querySelector('[data-cancel-own]');assert.ok(cancelButton);
 const cancelledId=cancelButton.dataset.cancelOwn;
 cancelButton.click();await new Promise(r=>setImmediate(r));
 assert.equal(records.get('reservations/'+cancelledId).cancelled,true);
 assert.equal(document.querySelectorAll('[data-cancel-own]').length,1);
 assert.match(document.querySelector('#my-history').textContent,/Cancelada/);
 records.set('days/'+week,{week,blocked:true,generation:1});notify();
 assert.match(document.querySelector('#my-history').textContent,/Cancelada por bloqueo/);
 authCallback({uid:'admin',email:domain.ADMIN_EMAIL,emailVerified:true,displayName:'Admin'});
 assert.equal(document.querySelector('#admin-nav').hidden,false);
 const originalCaption=document.querySelector('#week-caption').textContent;
 document.querySelector('#admin-week-next').click();
 const upcoming=management.shiftWeek(week,1);assert.equal(document.querySelector('#admin-week-date').value,upcoming);
 assert.equal(document.querySelector('#week-caption').textContent,originalCaption);
 document.querySelector('#activate-week').click();await new Promise(r=>setImmediate(r));
 assert.equal(records.get('days/'+upcoming).week,upcoming);
 assert.ok([...records].some(([p,r])=>p.startsWith('auditLogs/')&&r.event==='Habilitar semana'));
 document.querySelector('#admin-week-current').click();assert.equal(document.querySelector('#admin-week-date').value,week);
 document.querySelector('#admin-nav').click();assert.equal(document.querySelector('#admin-view').hidden,false);
 records.set('days/'+week,{week,blocked:false,generation:0});
 for(const [key,r]of records)if(key.startsWith('reservations/')&&r.uid==='student')records.set(key,{...r,cancelled:false});
 records.set('userActivity/student',{lastSeen:{seconds:1790856000,nanoseconds:0,toDate:()=>new Date('2026-10-01T12:00:00Z')}});notify();
 const markAttendance=checked=>{const control=document.querySelector('[data-attendance="student"]');assert.ok(control);control.checked=checked;control.dispatchEvent(new dom.window.Event('change',{bubbles:true}));};
 markAttendance(true);await new Promise(r=>setImmediate(r));
 assert.equal(records.get('attendance/student_'+week).present,true);
 assert.equal(document.querySelectorAll('[data-attendance="student"]:checked').length,2);
 let studentRow=document.querySelector('[data-delete-user="student"]').closest('tr');assert.equal(studentRow.cells[3].textContent,'1');assert.match(studentRow.cells[2].textContent,/1\/10\/26/);
 markAttendance(false);await new Promise(r=>setImmediate(r));
 studentRow=document.querySelector('[data-delete-user="student"]').closest('tr');assert.equal(studentRow.cells[3].textContent,'0');

 authCallback({uid:'admin2',email:'marchesemarialaura@gmail.com',emailVerified:true,displayName:'Laura'});
 assert.equal(document.querySelector('#admin-nav').hidden,false);
 authCallback({uid:'fakeadmin2',email:'marchesemarialaura@gmail.com',emailVerified:false});
 assert.equal(document.querySelector('#admin-nav').hidden,true);
 document.querySelector('#users-list').textContent='Dato privado anterior';
 document.querySelector('#profile-name').value='Persona anterior';
 authCallback(null);
 assert.equal(document.querySelector('#users-list').textContent,'');
 assert.equal(document.querySelector('#profile-name').value,'');
 records.set('users/student',{name:'<img src=x onerror=alert(1)>',condition:'Alumno regular',diet:'<script>alert(1)</script>',email:'student@example.com'});
 authCallback({uid:'admin',email:domain.ADMIN_EMAIL,emailVerified:true,displayName:'Admin'});
 assert.equal(document.querySelector('#users-list img'),null);
 assert.equal(document.querySelector('#users-list script'),null);
 assert.match(document.querySelector('#users-list').textContent,/<img src=x/);
 records.set('reservations/historical',{uid:'student',week:'2026-01-05',dateKey:'2026-01-05',shift:'mediodia',portions:1});
 document.querySelector('#download-backup').click();await new Promise(r=>setImmediate(r));
 assert.equal(capturedBackup.projectId,'appcomedor-6b4f7');
 assert.ok(capturedBackup.collections.reservations.some(r=>r.id==='historical'));
 assert.equal(Object.keys(capturedBackup.collections).length,9);
 capturedBackup=null;failBackupRead=true;document.querySelector('#download-backup').click();await new Promise(r=>setImmediate(r));
 assert.equal(capturedBackup,null);assert.match(document.querySelector('#backup-message').textContent,/No se pudo/);failBackupRead=false;
 document.querySelector('#user-search').value='sin coincidencias';document.querySelector('#user-search').dispatchEvent(new dom.window.Event('input',{bubbles:true}));assert.equal(document.querySelector('[data-delete-user="student"]'),null);
 document.querySelector('#user-search').value='';document.querySelector('#user-search').dispatchEvent(new dom.window.Event('input',{bubbles:true}));
 document.querySelector('#report-month').value=week.slice(0,7);document.querySelector('#monthly-generate').click();await new Promise(r=>setImmediate(r));assert.equal(document.querySelector('#monthly-csv').disabled,false);assert.match(document.querySelector('#monthly-results').textContent,/porciones solicitadas/);
 if(process.env.APP_UI_RENDER){document.querySelector('#admin-nav').click();fs.writeFileSync(process.env.APP_UI_RENDER,dom.serialize());}
 records.set('users/admin',{name:'Admin',condition:'Personal',diet:'',email:domain.ADMIN_EMAIL});
 records.set('users/admin2',{name:'Laura',condition:'Personal',diet:'',email:'marchesemarialaura@gmail.com'});
 notify();
 assert.equal(document.querySelector('[data-delete-user="admin"]'),null);
 assert.equal(document.querySelector('[data-delete-user="admin2"]'),null);
 document.querySelector('[data-delete-user="student"]').click();await new Promise(r=>setImmediate(r));
 assert.equal(records.has('users/student'),false);
 assert.equal([...records].some(([p,r])=>p.startsWith('reservations/')&&r.uid==='student'),false);
 records.set('users/guest1',{name:'Uno',condition:'Alumno regular',diet:'',email:'uno@example.com'});
 records.set('users/guest2',{name:'Dos',condition:'Alumno regular',diet:'',email:'dos@example.com'});notify();
 document.querySelector('#delete-all-users').click();await new Promise(r=>setImmediate(r));
 assert.equal(records.has('users/guest1'),false);assert.equal(records.has('users/guest2'),false);
 assert.equal(records.has('users/admin'),true);assert.equal(records.has('users/admin2'),true);
 records.set('modalities/curso',{name:'Curso',dates:[week],active:true});notify();
 document.querySelector('[data-delete-modality="curso"]').click();await new Promise(r=>setImmediate(r));
 assert.equal(records.has('modalities/curso'),false);
 records.set('users/template-student',{name:'Plantilla',condition:'Alumno regular',diet:'Sin TACC',email:'template@example.com'});
 for(const date of domain.weekDays(week))records.set('days/'+date,{week,blocked:false,generation:0});
 authCallback({uid:'template-student',email:'template@example.com',emailVerified:true});
 document.querySelector('#configure-template').click();assert.equal(document.querySelector('#week-template-dialog').open,true);
 document.querySelector('[data-template-day="1"][data-template-shift="mediodia"]').value='0';
 document.querySelector('[data-template-day="1"][data-template-shift="noche"]').value='2';
 document.querySelector('#week-template-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setImmediate(r));
 assert.equal(records.get('reservationPreferences/template-student').schedule['1'].noche,2);
 document.querySelector('#apply-template').click();assert.equal(document.querySelectorAll('[data-day]:checked').length,5);
 assert.equal([...records].filter(([p,r])=>p.startsWith('reservations/')&&r.uid==='template-student').length,0);
 document.querySelector('#save-button').click();await new Promise(r=>setImmediate(r));
 const savedTemplate=[...records].filter(([p,r])=>p.startsWith('reservations/')&&r.uid==='template-student').map(([,r])=>r);
 assert.equal(savedTemplate.length,10);assert.equal(savedTemplate.filter(r=>r.portions===2&&r.shift==='mediodia').length,4);
 assert.equal(savedTemplate.find(r=>r.dateKey===domain.weekDays(week)[1]&&r.shift==='noche').portions,2);
 document.querySelector('#configure-template').click();
 assert.equal(document.querySelector('[data-template-day="1"][data-template-shift="noche"]').value,'2');
 assert.equal(document.querySelector('[data-template-day="0"][data-template-shift="mediodia"]').value,'2');
 console.log('OK: eliminación individual, masiva, protección de ambos administradores y modalidad.');
 console.log('OK: UI sin sesión, rol alumno/admin, preferencias, ambos turnos, guardado y cancelación actualizada con SDK simulado.');
})().catch(e=>{console.error(e);process.exitCode=1});
